In [1]:
import glob
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats
import numpy as np
import cartopy.crs as ccrs
import cartopy.feature as cfeature
import seaborn as sns
from sklearn.metrics import mean_squared_error, r2_score
import pymc3 as pm
import arviz as az

In [6]:
COPEPOD80_BIOMASS = pd.read_csv('/net/meso/work/svivier/Git/Data/Biomass_IM_final.csv')

In [7]:
COPEPOD80_df_clean = pd.read_csv('/net/meso/work/svivier/Git/Data/Abundance_IM_final.csv')

In [8]:
COPEPOD80_BIOMASS

      Carbon Mass
0        2.878586
1       17.761304
2        2.517407
3       11.215845
4        8.311358
...           ...
1022     0.103977
1023     1.126274
1024     4.410456
1025     6.730864
1026     2.072564

[1027 rows x 1 columns]

In [9]:
COPEPOD80_df_clean

,Acartia,Acartia bifilosa,Acartia longiremis,Acartia spp.,Aetideopsis multiserrata,Aglantha digitale,Aglantha spp.,Alteutha interrupta,Augaptilus glacialis,Balanus balanus,...,Thysanoessa inermis,Thysanoessa longicaudata,Thysanoessa raschii,Thysanoessa spp.,Tisbe furcata,Undinella oblonga,Undinopsis spp.,Verruca spp.,Zaus goodsiri,Zaus spp.
0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0
1,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0
2,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0
3,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0
4,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1022,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0
1023,0.0,0.0,0.0,0.19,0.0,0.0,0.0,0.0,0.0,0.0,...,0.37,0.0,0.0,0.0,0.0,0.0,0.19,0.38,0.0,0.0
1024,0.0,0.0,0.0,16.74,0.0,0.0,0.0,0.0,0.0,0.0,...,0.93,0.0,0.0,0.0,0.0,0.0,2.79,3.72,0.0,0.0
1025,0.0,0.0,0.0,16.12,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00,0.0,0.0,0.0,0.0,0.0,0.62,31.63,0.0,0.0
1026,0.0,0.0,0.0,8.18,0.0,0.0,0.0,0.0,0.0,0.0,...,0.37,0.0,0.0,0.0,0.0,0.0,0.37,4.09,0.0,0.0

# 1% + We create the simulated data: Simulated Abundance data = COPEPOD80_df_clean; Simulated Total Biomass data: COPEPOD80_df_clean x ICWs AtlantECO
We simulate data using our abundance data and the ICWs of AtlantECO=> We can test our model

Here, All species that has a maximum abundance <1% in each samples are grouped in Size groups (=1; <1; <<1)

In [12]:
groupes = {
    '=1': ['Aetideopsis multiserrata', 'Chiridius obtusifrons', 'Gaetanus brevispinus', 'Paraheterorhabdus compactus', 'Eukrohnia hamata', 'Rathkea spp.', 'Sarsia princeps', 'Sarsia spp.', 'Sarsia tubulosa'],
    '<1': [ 'Mimocalanus distinctocephalus','Pseudochirella spectabilis', 'Aglantha spp.', 'Candacia armata', 'Haloptilus acutifrons', 'Heterorhabdus norvegicus', 'Mormonilla minor', 'Spinocalanus magnus', 'Spinocalanus spinosus'], 
    '<<1': ['Alteutha interrupta', 'Cyclopina longicornis', 'Danielssenia typica', 'Harpacticus chelifer', 'Zaus goodsiri', 'Zaus spp.', 'Laophonte perplexa', 'Lubbockia glacialis', 'Parathalestris croni', 'Parathalestris harpactoides', 'Rhynchothalestris helgolandica', 'Tegastes falcatus'],
    'inconnu': ['Euphysa spp.','Syllides spp.','Rathkea octopunctata','Discoconchoecia elegans','Cladocera', 'Erythrops erythrophthalma', 'Erythrops spp.', 'Gaidius tenuispinus', 'Hyas', 'Hyperoche medusarum', 'Lepas spp.', 'Staurophora spp.'],
    'Acartia': ['Acartia bifilosa', 'Acartia longiremis', 'Acartia spp.', 'Aglantha digitale', 'Acartia'],
    'Metridia': ['Metridia longa', 'Metridia lucens', 'Metridia spp.'],
    'Microcalanus': ['Microcalanus pusillus', 'Microcalanus pygmaeus', 'Microcalanus spp.'],
    'Temora': ['Temora longicornis', 'Temora spp.'],
    'Oithona': ['Oithona atlantica', 'Oithona similis', 'Oithona spp.', 'Oithona frigida'],
    'Limacina': ['Limacina retroversa', 'Limacina spp.', 'Limacina helicina', 'Clione limacina', 'Limacina','Clione'],
    'Balanus': ['Balanus balanus', 'Balanus crenatus', 'Balanus spp.'],
    'Evadne': ['Evadne nordmanni', 'Evadne spp.'],
    'Sagitta': ['Parasagitta elegans', 'Sagitta spp.'],
    'Thysanoessa': ['Thysanoessa inermis', 'Thysanoessa longicaudata', 'Thysanoessa raschii', 'Thysanoessa spp.'],
    'Centropages': ['Centropages hamatus', 'Centropages spp.', 'Centropages typicus'],
    'Pseudocalanus': ['Pseudocalanus elongatus', 'Pseudocalanus gracilis', 'Pseudocalanus spp.'],
    'Euchaeta': ['Euchaeta spp.'],
    'Eukrohnia': ['Eukrohnia spp.'],
    'Fritillaria': ['Fritillaria', 'Fritillaria borealis', 'Fritillaria spp.'],
    'Hyperiidea': ['Hyperia spp.', 'Hyperiidea'],
    'Beroe': ['Beroe spp.'],
    'Bolinopsis': ['Bolinopsis spp.'],
    'Bradyidius': ['Bradyidius similis'],
    'Monstrilla': ['Monstrilla spp.'],
    'Oncaea': ['Oncaea borealis', 'Oncaea notopus', 'Oncaea spp.'],
    'Pagurus': ['Pagurus spp.'],
    'Paracalanus': ['Paracalanus spp.'],
    'Paraeuchaeta': ['Paraeuchaeta glacialis', 'Paraeuchaeta norvegica'],
    'Pleurobrachia': ['Pleurobrachia spp.'],
    'Podon': ['Podon spp.','Podon leuckartii'],
    'Polychaeta': ['Polychaeta'],
    'Spinocalanus': ['Spinocalanus abyssalis', 'Spinocalanus sp.'],
    'Thalestris': ['Thalestris gibba'],
    'Tisbe': ['Tisbe furcata'],
    'Undinella': ['Undinella oblonga'],
    'Verruca': ['Verruca spp.'],
    'Augaptilus': ['Augaptilus glacialis'],
    'Bradyidius': ['Bradyidius similis'],
    'Chaetognatha': ['Chaetognatha'],
    'Obelia': ['Obelia geniculata',  'Obelia longissima', 'Obelia spp.'],
    'Oikopleura': ['Oikopleura', 'Oikopleura labradoriensis', 'Oikopleura spp.'],
    'Pagurus': ['Pagurus spp.'],
    'Plotocnide': ['Plotocnide borealis', 'Plotocnide spp.'],
    'Scaphocalanus': ['Scaphocalanus brevicornis', 'Scaphocalanus magnus'],
    'Semibalanus': ['Semibalanus balanoides'],
    'Themisto': ['Themisto abyssorum', 'Themisto spp.'],
    'Thysanoessa': ['Thysanoessa inermis', 'Thysanoessa longicaudata', 'Thysanoessa raschii', 'Thysanoessa spp.'],
    'Undinopsis': ['Undinopsis spp.'],
    'Meganyctiphanes': ['Meganyctiphanes norvegica', 'Meganyctiphanes spp.'],
    'Harpacticus': ['Harpacticus littoralis', 'Harpacticus spp.']


    
    

    

    
}
COPEPOD80_reduite = pd.DataFrame(index=COPEPOD80_df_clean.index)

for groupe, especes in groupes.items():
    # VÃ©rifier si les espÃ¨ces du groupe sont prÃ©sentes dans le DataFrame d'abondance
    especes_presentes = [espece for espece in especes if espece in COPEPOD80_df_clean.columns]
    if especes_presentes:
        # Somme des abondances pour les espÃ¨ces prÃ©sentes dans le groupe
        COPEPOD80_reduite[groupe] = COPEPOD80_df_clean[especes_presentes].sum(axis=1)

# Ajouter les espÃ¨ces qui ne sont pas dans les groupes
for espece in COPEPOD80_df_clean.columns:
    if not any(espece in especes for especes in groupes.values()):
        COPEPOD80_reduite[espece] = COPEPOD80_df_clean[espece]

In [13]:
#=Priors corrigÃ©e: /10 les priors des copepods

priors = {
    '=1': {'mu': 1, 'sigma': 1},
    '<1': {'mu': 0.1, 'sigma': 0.1},
    '<<1': {'mu': 0.01, 'sigma': 0.01},
    'inconnu': {'sigma': 1},
    'Limacina': {'sigma': 1},
    'Undinopsis': {'sigma': 1},
    'Balanus': {'sigma': 5},
    'Evadne': {'sigma': 5},
    'Verruca': {'sigma':1},
    'Fritillaria': {'sigma': 1},
    'Copepoda':{'sigma':1},
    'Beroe': {'mu': 7.12, 'sigma': 10},
    'Acartia': {'mu': 0.003, 'sigma': 0.1},
    'Metridia': {'mu': 0.08, 'sigma': 0.1},
    'Paracalanus': {'mu': 0.0016, 'sigma': 0.01},
    'Temora': {'mu': 0.001, 'sigma': 0.01},
    'Oithona': {'mu': 0.0005, 'sigma': 0.01},
    'Spinocalanus': {'mu': 0.2, 'sigma': 0.2},
    'Centropages': {'mu': 0.0075, 'sigma': 0.1},
    'Sagitta': {'mu': 0.6, 'sigma': 1}, #Chaetognatha
    'Pseudocalanus': {'mu': 0.004, 'sigma': 0.1},
    'Thysanoessa': {'mu': 6, 'sigma': 6}, #Euphosiacea
    'Oikopleura': {'mu': 0.006, 'sigma': 0.01},
    'Microcalanus': {'mu': 0.0002, 'sigma': 0.01},
    'Microsetella spp.': {'mu': 0.0008, 'sigma': 0.01},
    'Calanus finmarchicus': {'mu': 0.2, 'sigma': 1},
    'Calanus glacialis': {'mu': 0.2, 'sigma': 1},
    'Calanus hyperboreus': {'mu': 1.7, 'sigma': 1},
    'Bradyidius': {'mu': 0.3, 'sigma': 1},
    'Semibalanus': {'sigma': 5},
    'Chaetognatha': {'mu': 1, 'sigma': 1},
    'Euchaeta':  {'mu': 0.14, 'sigma': 1},
    'Eukrohnia': {'mu': 1.4, 'sigma': 1.4},
    'Hyperiidea':{'mu': 20, 'sigma': 20},
    'Themisto': {'mu': 1.4, 'sigma': 1.4},
    'Bolinopsis': {'mu': 40, 'sigma': 10},
    'Monstrilla': {'mu': 0.1, 'sigma': 1},
    'Oncaea': {'mu': 0.001, 'sigma': 0.1},
    'Pagurus':{'sigma': 5},
    'Paraeuchaeta': {'mu': 1, 'sigma': 1},
    'Pleurobrachia': {'mu': 2, 'sigma': 2},
    'Podon': {'sigma': 1},
    'Polychaeta':{'mu': 0.05, 'sigma': 0.05},
    'Thalestris':{'mu': 0.001, 'sigma': 0.01},
    'Tisbe':{'mu': 0.001, 'sigma': 0.01},
    'Undinella':{'mu': 0.3, 'sigma': 1},
    'Augaptilus':{'mu': 0.3, 'sigma': 1}, 
    'Obelia':{'mu': 1, 'sigma': 1},
    'Plotocnide':{'mu': 1, 'sigma': 1}, 
    'Scaphocalanus':{'mu': 0.2, 'sigma': 1},
    'Meganyctiphanes':{'mu': 10, 'sigma': 10}, 
    'Harpacticus':{'mu': 0.001, 'sigma': 0.01},
    'Calanus spp.':{'mu': 0.7, 'sigma': 0.7}, 
    'Gammaridea':{'mu': 3, 'sigma': 3}, 
    'Hormiphora cucumis':{'mu': 10, 'sigma': 10},
    'Hyas spp.':{'sigma': 1}, 
    'Jaschnovia tolli':{'mu': 3, 'sigma': 3}, 
    'Microsetella spp.':{'mu': 0.001, 'sigma': 0.01},
    'Scolecithricella minor':{'mu': 0.1, 'sigma': 0.1}, 
    'Spionidae spp.':{'sigma': 1}, 
    'Temorites brevis':{'mu': 0.3, 'sigma': 1}
    
    
    


    
    

}

In [15]:
# SpeciesCmass: the ICWs used to simulate the total biomass of the samples = ICWs of AtlantECO if available, 1 if not.

import pandas as pd

# CrÃ©er une liste pour stocker les tuples (espÃ¨ce, valeur)
data = []

for species, values in priors.items():
    # SÃ©lectionner 'mu' s'il est prÃ©sent, sinon 'sigma'
    value = values.get('mu', values['sigma'])
    data.append((species, value))

# CrÃ©er un DataFrame Ã  partir de la liste des tuples
SpeciesCmass = pd.DataFrame(data, columns=['Species', 'Value']).set_index('Species')

# Affichage du DataFrame
SpeciesCmass

                          Value
Species
=1                       1.0000
<1                       0.1000
<<1                      0.0100
inconnu                  1.0000
Limacina                 1.0000
Undinopsis               1.0000
Balanus                  5.0000
Evadne                   5.0000
Verruca                  1.0000
Fritillaria              1.0000
Copepoda                 1.0000
Beroe                    7.1200
Acartia                  0.0030
Metridia                 0.0800
Paracalanus              0.0016
Temora                   0.0010
Oithona                  0.0005
Spinocalanus             0.2000
Centropages              0.0075
Sagitta                  0.6000
Pseudocalanus            0.0040
Thysanoessa              6.0000
Oikopleura               0.0060
Microcalanus             0.0002
Microsetella spp.        0.0010
Calanus finmarchicus     0.2000
Calanus glacialis        0.2000
Calanus hyperboreus      1.7000
Bradyidius               0.3000
Semibalanus              5.0000
Chaetognatha             1.0000
Euchaeta                 0.1400
Eukrohnia                1.4000
Hyperiidea              20.0000
Themisto                 1.4000
Bolinopsis              40.0000
Monstrilla               0.1000
Oncaea                   0.0010
Pagurus                  5.0000
Paraeuchaeta             1.0000
Pleurobrachia            2.0000
Podon                    1.0000
Polychaeta               0.0500
Thalestris               0.0010
Tisbe                    0.0010
Undinella                0.3000
Augaptilus               0.3000
Obelia                   1.0000
Plotocnide               1.0000
Scaphocalanus            0.2000
Meganyctiphanes         10.0000
Harpacticus              0.0010
Calanus spp.             0.7000
Gammaridea               3.0000
Hormiphora cucumis      10.0000
Hyas spp.                1.0000
Jaschnovia tolli         3.0000
Scolecithricella minor   0.1000
Spionidae spp.           1.0000
Temorites brevis         0.3000

In [18]:
import pandas as pd


# Assurez-vous que les indices de SpeciesCmass correspondent aux colonnes de COPEPOD80_reduite
SpeciesCmass = SpeciesCmass.reindex(COPEPOD80_reduite.columns)

# Calculer la biomasse totale pour chaque Ã©chantillon
RealTotalCmass = (COPEPOD80_reduite * SpeciesCmass['Value']).sum(axis=1)

In [19]:
RealTotalCmass

0        10.450000
1       105.770000
2         5.900000
3        51.610000
4        43.200000
           ...
1022      0.004277
1023      7.553807
1024     35.969606
1025     75.938797
1026     14.852089
Length: 1027, dtype: float64

In [20]:
ABONDANCE_sampled = COPEPOD80_reduite.values.astype(float)
BIOMASS_sampled = RealTotalCmass.values.flatten()

with pm.Model() as model:
    biomasses = {}
    PositiveNormal = pm.Bound(pm.Normal, lower=0.0)
    

    for species, params in priors.items():
        # Utiliser une distribution normale si un 'mu' est spÃ©cifiÃ©
        if 'mu' in params:
            biomasses[species] = PositiveNormal(species, mu=params['mu'], sigma=params['sigma'])
        else:
            # Utiliser une distribution HalfNormal sinon
            biomasses[species] = pm.HalfNormal(species, sigma=params['sigma'])

    # CrÃ©er un vecteur de biomasses dans le mÃªme ordre que les colonnes de ABONDANCE_sampled
    biomass_vector = [biomasses[species] for species in COPEPOD80_reduite.columns if species in biomasses]

# Calculer la biomasse prÃ©dite
    predicted_biomass = pm.math.dot(ABONDANCE_sampled, pm.math.stack(biomass_vector))


    # Likelihood: Comparaison de la biomasse prÃ©dite avec la biomasse observÃ©e
    observed = pm.Normal('observed', mu=predicted_biomass, sigma=50, observed=BIOMASS_sampled)

    # ExÃ©cution de l'Ã©chantillonneur
    trace = pm.sample(1000, return_inferencedata=False)

Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [Temorites brevis, Spionidae spp., Scolecithricella minor, Jaschnovia tolli, Hyas spp., Hormiphora cucumis, Gammaridea, Calanus spp., Harpacticus, Meganyctiphanes, Scaphocalanus, Plotocnide, Obelia, Augaptilus, Undinella, Tisbe, Thalestris, Polychaeta, Podon, Pleurobrachia, Paraeuchaeta, Pagurus, Oncaea, Monstrilla, Bolinopsis, Themisto, Hyperiidea, Eukrohnia, Euchaeta, Chaetognatha, Semibalanus, Bradyidius, Calanus hyperboreus, Calanus glacialis, Calanus finmarchicus, Microsetella spp., Microcalanus, Oikopleura, Thysanoessa, Pseudocalanus, Sagitta, Centropages, Spinocalanus, Oithona, Temora, Paracalanus, Metridia, Acartia, Beroe, Copepoda, Fritillaria, Verruca, Evadne, Balanus, Undinopsis, Limacina, inconnu, <<1, <1, =1]

Sampling 4 chains for 1_000 tune and 1_000 draw iterations (4_000 + 4_000 draws total) took 247 seconds.

In [21]:
summarry=pm.summary(trace)
# Extraire les moyennes et les intervalles HDI pour chaque variable de biomasse
biomass_means = summarry['mean']
hdi_3 = summarry['hdi_3%']
hdi_97 = summarry['hdi_97%']

# CrÃ©er un DataFrame Ã  partir des informations extraites
results_df = pd.DataFrame({
    'Espece': biomass_means.index,
    'Biomasse moyenne': biomass_means.values,
    'HDI 3%': hdi_3.values,
    'HDI 97%': hdi_97.values
})

# Mettre 'Identifiant' en tant qu'indice du DataFrame
results_df.set_index('Espece', inplace=True)

# Afficher les rÃ©sultats avec 'Identifiant' comme indice
results_df

Got error No model on context stack. trying to find log_likelihood in translation.
/home/svivier/.conda/envs/sebpy/lib/python3.9/site-packages/arviz/data/io_pymc3_3x.py:98: FutureWarning: Using `from_pymc3` without the model will be deprecated in a future release. Not using the model will return less accurate and less useful results. Make sure you use the model argument or call from_pymc3 within a model context.
  warnings.warn(

                        Biomasse moyenne  HDI 3%  HDI 97%
Espece
=1                                 1.270   0.002    2.657
<1                                 0.130   0.000    0.263
<<1                                0.013   0.000    0.026
inconnu                            0.796   0.000    1.887
Limacina                           0.921   0.369    1.415
Undinopsis                         0.791   0.000    1.808
Balanus                            4.765   3.867    5.622
Evadne                             4.838   3.114    6.481
Verruca                            0.918   0.375    1.458
Fritillaria                        0.939   0.300    1.566
Copepoda                           0.779   0.001    1.834
Beroe                              7.112   6.698    7.564
Acartia                            0.074   0.000    0.172
Metridia                           0.095   0.002    0.191
Paracalanus                        0.008   0.000    0.020
Temora                             0.008   0.000    0.019
Oithona                            0.007   0.000    0.018
Spinocalanus                       0.256   0.000    0.531
Centropages                        0.082   0.000    0.188
Sagitta                            0.631   0.018    1.212
Pseudocalanus                      0.009   0.000    0.019
Thysanoessa                        6.011   5.773    6.227
Oikopleura                         0.011   0.000    0.023
Microcalanus                       0.008   0.000    0.019
Microsetella spp.                  0.008   0.000    0.019
Calanus finmarchicus               0.200   0.189    0.209
Calanus glacialis                  0.375   0.000    0.835
Calanus hyperboreus                1.520   0.420    2.654
Bradyidius                         0.934   0.001    2.065
Semibalanus                        3.901   0.007    8.331
Chaetognatha                       1.282   0.003    2.565
Euchaeta                           0.853   0.000    1.961
Eukrohnia                          1.825   0.022    3.717
Hyperiidea                        21.890   0.007   41.439
Themisto                           1.804   0.003    3.681
Bolinopsis                        39.870  33.489   45.930
Monstrilla                         0.850   0.001    1.957
Oncaea                             0.079   0.000    0.188
Pagurus                            3.868   0.010    8.823
Paraeuchaeta                       1.285   0.003    2.647
Pleurobrachia                      2.334   0.005    4.662
Podon                              0.796   0.000    1.869
Polychaeta                         0.065   0.001    0.131
Thalestris                         0.008   0.000    0.020
Tisbe                              0.008   0.000    0.020
Undinella                          0.914   0.001    2.079
Augaptilus                         0.900   0.000    2.073
Obelia                             1.268   0.006    2.588
Plotocnide                         1.281   0.000    2.614
Scaphocalanus                      0.881   0.000    2.005
Meganyctiphanes                   12.200   0.041   25.165
Harpacticus                        0.009   0.000    0.020
Calanus spp.                       0.657   0.001    1.283
Gammaridea                         3.877   0.022    7.878
Hormiphora cucumis                10.972   0.587   20.433
Hyas spp.                          0.809   0.001    1.884
Jaschnovia tolli                   3.760   0.002    7.870
Scolecithricella minor             0.131   0.000    0.266
Spionidae spp.                     0.792   0.001    1.907
Temorites brevis                   0.914   0.000    2.088

In [22]:
# Initialisation d'une liste pour stocker les donnÃ©es
especes_data = []

# ItÃ©rer sur chaque groupe et chaque espÃ¨ce dans le groupe
for groupe, biomasse_data in results_df.iterrows():
    # Si le groupe est dans le dictionnaire groupes, itÃ©rer sur les espÃ¨ces
    if groupe in groupes:
        for espece in groupes[groupe]:
            especes_data.append({
                'Espece': espece,
                'Biomasse moyenne': biomasse_data['Biomasse moyenne'],
                'HDI 3%': biomasse_data['HDI 3%'],
                'HDI 97%': biomasse_data['HDI 97%']
            })
    else:
        # Si le groupe n'est pas dans groupes, l'ajouter directement comme espÃ¨ce
        especes_data.append({
            'Espece': groupe,
            'Biomasse moyenne': biomasse_data['Biomasse moyenne'],
            'HDI 3%': biomasse_data['HDI 3%'],
            'HDI 97%': biomasse_data['HDI 97%']
        })

# CrÃ©er le DataFrame Ã  partir de la liste de dictionnaires
results_df_especes = pd.DataFrame(especes_data)

# Mettre 'EspÃ¨ce' en tant qu'indice du DataFrame
results_df_especes.set_index('Espece', inplace=True)

# Afficher les rÃ©sultats
results_df_especes

                             Biomasse moyenne  HDI 3%  HDI 97%
Espece
Aetideopsis multiserrata                1.270   0.002    2.657
Chiridius obtusifrons                   1.270   0.002    2.657
Gaetanus brevispinus                    1.270   0.002    2.657
Paraheterorhabdus compactus             1.270   0.002    2.657
Eukrohnia hamata                        1.270   0.002    2.657
...                                       ...     ...      ...
Hyas spp.                               0.809   0.001    1.884
Jaschnovia tolli                        3.760   0.002    7.870
Scolecithricella minor                  0.131   0.000    0.266
Spionidae spp.                          0.792   0.001    1.907
Temorites brevis                        0.914   0.000    2.088

[143 rows x 3 columns]

In [24]:
groupes = {
    'unknow': ['Hyas spp.','Syllides spp.','Cladocera', 'Erythrops erythrophthalma', 'Erythrops spp.', 'Gaidius tenuispinus', 'Hyas', 'Hyperoche medusarum', 'Lepas spp.', 'Staurophora spp.'],
    'Acartia': ['Acartia bifilosa', 'Acartia longiremis', 'Acartia spp.', 'Aglantha digitale', 'Acartia'],
    'Metridia': ['Metridia longa', 'Metridia lucens', 'Metridia spp.'],
    'Microcalanus': ['Microcalanus pusillus', 'Microcalanus pygmaeus', 'Microcalanus spp.'],
    'Temora': ['Temora longicornis', 'Temora spp.'],
    'Oithona': ['Oithona atlantica', 'Oithona similis', 'Oithona spp.', 'Oithona frigida'],
    'Limacina': ['Limacina retroversa', 'Limacina spp.', 'Limacina helicina', 'Clione limacina', 'Limacina','Clione'],
    'Balanus': ['Balanus balanus', 'Balanus crenatus', 'Balanus spp.'],
    'Evadne': ['Evadne nordmanni', 'Evadne spp.'],
    'Sagitta': ['Parasagitta elegans', 'Sagitta spp.'],
    'Thysanoessa': ['Thysanoessa inermis', 'Thysanoessa longicaudata', 'Thysanoessa raschii', 'Thysanoessa spp.'],
    'Centropages': ['Centropages hamatus', 'Centropages spp.', 'Centropages typicus'],
    'Pseudocalanus': ['Pseudocalanus elongatus', 'Pseudocalanus gracilis', 'Pseudocalanus spp.'],
    'Euchaeta': ['Euchaeta spp.'],
    'Eukrohnia': ['Eukrohnia spp.', 'Eukrohnia hamata'],
    'Fritillaria': ['Fritillaria', 'Fritillaria borealis', 'Fritillaria spp.'],
    'Hyperiidea': ['Hyperia spp.', 'Hyperiidea'],
    'Beroe': ['Beroe spp.'],
    'Bolinopsis': ['Bolinopsis spp.'],
    'Bradyidius': ['Bradyidius similis'],
    'Monstrilla': ['Monstrilla spp.'],
    'Oncaea': ['Oncaea borealis', 'Oncaea notopus', 'Oncaea spp.'],
    'Pagurus': ['Pagurus spp.'],
    'Paracalanus': ['Paracalanus spp.'],
    'Paraeuchaeta': ['Paraeuchaeta glacialis', 'Paraeuchaeta norvegica'],
    'Pleurobrachia': ['Pleurobrachia spp.'],
    'Podon': ['Podon spp.', 'Podon leuckartii'],
    'Polychaeta': ['Polychaeta'],
    'Spinocalanus': ['Spinocalanus abyssalis', 'Spinocalanus sp.'],
    'Thalestris': ['Thalestris gibba'],
    'Tisbe': ['Tisbe furcata'],
    'Undinella': ['Undinella oblonga'],
    'Verruca': ['Verruca spp.'],
    'Augaptilus': ['Augaptilus glacialis'],
    'Bradyidius': ['Bradyidius similis'],
    'Chaetognatha': ['Chaetognatha'],
    'Obelia': ['Obelia geniculata',  'Obelia longissima', 'Obelia spp.'],
    'Oikopleura': ['Oikopleura', 'Oikopleura labradoriensis', 'Oikopleura spp.'],
    'Pagurus': ['Pagurus spp.'],
    'Plotocnide': ['Plotocnide borealis', 'Plotocnide spp.'],
    'Scaphocalanus': ['Scaphocalanus brevicornis', 'Scaphocalanus magnus'],
    'Semibalanus': ['Semibalanus balanoides'],
    'Themisto': ['Themisto abyssorum', 'Themisto spp.'],
    'Thysanoessa': ['Thysanoessa inermis', 'Thysanoessa longicaudata', 'Thysanoessa raschii', 'Thysanoessa spp.'],
    'Undinopsis': ['Undinopsis spp.'],
    'Meganyctiphanes': ['Meganyctiphanes norvegica', 'Meganyctiphanes spp.'],
    'Harpacticus': ['Harpacticus littoralis', 'Harpacticus spp.'],
    'Sarsia':['Sarsia princeps', 'Sarsia spp.', 'Sarsia tubulosa'],
    'Spinocalanus': ['Spinocalanus magnus', 'Spinocalanus spinosus','Spinocalanus abyssalis'],
    'Zaus': ['Harpacticus chelifer', 'Zaus goodsiri', 'Zaus spp.'],
    'Parathalestris': ['Parathalestris croni', 'Parathalestris harpactoides'],
    'Rathkea': ['Rathkea octopunctata', 'Rathkea spp.'],
    
    
    
    


    


    
    

    

    
}

# CrÃ©er un DataFrame pour stocker les rÃ©sultats groupÃ©s
grouped_results = pd.DataFrame(columns=['Biomasse moyenne (group 1%)', 'HDI 3% (group 1%)', 'HDI 97% (group 1%)'])

# ItÃ©rer sur les groupes pour calculer les statistiques
for groupe, especes in groupes.items():
    if any(espece in results_df_especes.index for espece in especes):
        data_subset = results_df_especes.loc[results_df_especes.index.intersection(especes)]
        grouped_results.loc[groupe] = {
            'Biomasse moyenne (group 1%)': data_subset['Biomasse moyenne'].mean(),
            'HDI 3% (group 1%)': data_subset['HDI 3%'].mean(),
            'HDI 97% (group 1%)': data_subset['HDI 97%'].mean()
        }

# Traiter les espÃ¨ces non groupÃ©es
for espece in results_df_especes.index:
    if espece not in sum(groupes.values(), []):
        grouped_results.loc[espece] = {
            'Biomasse moyenne (group 1%)': results_df_especes.at[espece, 'Biomasse moyenne'],
            'HDI 3% (group 1%)': results_df_especes.at[espece, 'HDI 3%'],
            'HDI 97% (group 1%)': results_df_especes.at[espece, 'HDI 97%']
        }

# Afficher les rÃ©sultats
f1=grouped_results.copy()

In [25]:
f1

,Biomasse moyenne (group 1%),HDI 3% (group 1%),HDI 97% (group 1%)
unknow,0.7973,0.0001,1.8867
Acartia,0.0740,0.0000,0.1720
Metridia,0.0950,0.0020,0.1910
Microcalanus,0.0080,0.0000,0.0190
Temora,0.0080,0.0000,0.0190
...,...,...,...
Hormiphora cucumis,10.9720,0.5870,20.4330
Jaschnovia tolli,3.7600,0.0020,7.8700
Scolecithricella minor,0.1310,0.0000,0.2660
Spionidae spp.,0.7920,0.0010,1.9070
Temorites brevis,0.9140,0.0000,2.0880